import {
  PROJECT_CHAT_IMAGE_MIME_TYPES,
  PROJECT_CHAT_MAX_IMAGE_BYTES,
  PROJECT_CHAT_MAX_IMAGES,
  type ProjectChatImageMimeType,
  type ChatImageReference,
  type StoredChatImage,
} from './project-chat-contracts.ts'

export const PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH = 120

export type ProjectChatImageUploadMetadata = {
  name: string
  size: number
  type?: string | null
}

export type NormalizedProjectChatImageUpload = {
  name: string
  size: number
  mimeType: ProjectChatImageMimeType
}

export type ProjectChatImageValidation =
  | { ok: true; files: NormalizedProjectChatImageUpload[] }
  | { ok: false; error: string }

export type ProjectChatMessageInput = {
  body: string | null
  images: ChatImageReference[]
}

export type ProjectChatMessageInputValidation =
  | { ok: true; data: ProjectChatMessageInput }
  | { ok: false; error: string }

const EXTENSION_MIME_TYPES: Record<string, ProjectChatImageMimeType> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
}

const PATH_NAME_PATTERN = '[A-Za-z0-9._() -]'
// The UUID is generated by crypto.randomUUID, but accepting every canonical
// UUID form here keeps cleanup compatible with deterministic test fixtures and
// older upload records.
const UUID_PATTERN = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

export function sanitizeProjectChatImageName(name: string): string {
  const cleaned = name
    .trim()
    .replace(/[\\/]+/g, '_')
    .replace(/[^A-Za-z0-9._() -]+/g, '_')
    .replace(/\s+/g, ' ')
    .trim()
  const extensionStart = cleaned.lastIndexOf('.')
  const hasExtension = extensionStart > 0 && extensionStart < cleaned.length - 1
  const sanitized = cleaned.length <= PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH
    ? cleaned
    : hasExtension && cleaned.length - extensionStart <= PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH
      ? `${cleaned.slice(0, PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH - (cleaned.length - extensionStart))}${cleaned.slice(extensionStart)}`
      : cleaned.slice(0, PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH)

  // Avoid a path-like name that has no useful filename after sanitization.
  return /^\.+$/.test(sanitized) ? '_' : sanitized
}

export function mimeTypeFromProjectChatImageName(name: string): ProjectChatImageMimeType | null {
  const dot = name.lastIndexOf('.')
  if (dot < 0) return null
  return EXTENSION_MIME_TYPES[name.slice(dot).toLowerCase()] ?? null
}

export function normalizeProjectChatImageMimeType(
  name: string,
  type?: string | null,
): ProjectChatImageMimeType | null {
  const normalizedType = typeof type === 'string' ? type.trim().toLowerCase() : ''
  const extensionMimeType = mimeTypeFromProjectChatImageName(name)

  // An omitted MIME is only safe to infer from an explicitly permitted suffix.
  if (!normalizedType) return extensionMimeType
  if (!PROJECT_CHAT_IMAGE_MIME_TYPES.includes(normalizedType as ProjectChatImageMimeType)) return null
  if (extensionMimeType && extensionMimeType !== normalizedType) return null
  return normalizedType as ProjectChatImageMimeType
}

export function validateProjectChatImageUploads(value: unknown): ProjectChatImageValidation {
  if (!Array.isArray(value) || value.length < 1 || value.length > PROJECT_CHAT_MAX_IMAGES) {
    return { ok: false, error: `files[] must contain 1..${PROJECT_CHAT_MAX_IMAGES} images` }
  }

  const files: NormalizedProjectChatImageUpload[] = []
  for (const [index, raw] of value.entries()) {
    if (!raw || typeof raw !== 'object') {
      return { ok: false, error: `Invalid image metadata at index ${index}` }
    }

    const file = raw as Partial<ProjectChatImageUploadMetadata>
    if (typeof file.name !== 'string' || !file.name.trim()) {
      return { ok: false, error: `Image ${index + 1} must have a non-empty name` }
    }
    const name = sanitizeProjectChatImageName(file.name)
    if (!name || name.length > PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH) {
      return { ok: false, error: `Image ${index + 1} has an invalid name` }
    }
    if (
      typeof file.size !== 'number' ||
      !Number.isSafeInteger(file.size) ||
      file.size < 1 ||
      file.size > PROJECT_CHAT_MAX_IMAGE_BYTES
    ) {
      return { ok: false, error: `Image ${index + 1} must be between 1 byte and 10 MB` }
    }
    if (file.type !== undefined && file.type !== null && typeof file.type !== 'string') {
      return { ok: false, error: `Image ${index + 1} has an invalid MIME type` }
    }

    const mimeType = normalizeProjectChatImageMimeType(name, file.type)
    if (!mimeType) {
      return { ok: false, error: `Image ${index + 1} must be PNG, JPEG, WebP, or GIF` }
    }

    files.push({ name, size: file.size, mimeType })
  }

  return { ok: true, files }
}

export function projectChatImagePrefix(projectId: string, userId: string): string {
  return `projects/${projectId}/chat/${userId}/`
}

export function buildProjectChatImagePath(
  projectId: string,
  userId: string,
  name: string,
  id = crypto.randomUUID(),
): string {
  return `${projectChatImagePrefix(projectId, userId)}${id}_${sanitizeProjectChatImageName(name)}`
}

export function isProjectChatImagePath(path: unknown, projectId: string, userId: string): path is string {
  if (typeof path !== 'string') return false
  const prefix = projectChatImagePrefix(projectId, userId)
  if (!path.startsWith(prefix)) return false
  const suffix = path.slice(prefix.length)
  const pattern = new RegExp(`^${UUID_PATTERN}_${PATH_NAME_PATTERN}{1,${PROJECT_CHAT_MAX_IMAGE_NAME_LENGTH}}$`, 'i')
  return pattern.test(suffix)
}

export function isCoherentProjectChatImageReference(
  path: unknown,
  name: unknown,
  projectId: string,
  userId: string,
): path is string {
  if (typeof name !== 'string' || !name.trim() || !isProjectChatImagePath(path, projectId, userId)) {
    return false
  }
  const suffix = path.slice(projectChatImagePrefix(projectId, userId).length)
  const separator = suffix.indexOf('_')
  return separator > 0 && suffix.slice(separator + 1) === sanitizeProjectChatImageName(name)
}

export function parseProjectChatMessageInput(
  value: unknown,
  projectId: string,
  userId: string,
): ProjectChatMessageInputValidation {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { ok: false, error: 'Invalid body' }
  }
  const input = value as { body?: unknown; images?: unknown }

  let body: string | null = null
  if (input.body !== undefined && input.body !== null) {
    if (typeof input.body !== 'string') return { ok: false, error: 'body must be a string or null' }
    body = input.body.trim() || null
    if (body && body.length > 5000) return { ok: false, error: 'body is too long (max 5000 chars)' }
  }

  const rawImages = input.images === undefined ? [] : input.images
  if (!Array.isArray(rawImages) || rawImages.length > PROJECT_CHAT_MAX_IMAGES) {
    return { ok: false, error: `images[] must contain at most ${PROJECT_CHAT_MAX_IMAGES} images` }
  }

  const images: ChatImageReference[] = []
  const paths = new Set<string>()
  for (const raw of rawImages) {
    if (!raw || typeof raw !== 'object') return { ok: false, error: 'Invalid image reference' }
    const image = raw as { path?: unknown; name?: unknown }
    if (typeof image.path !== 'string' || typeof image.name !== 'string') {
      return { ok: false, error: 'Each image requires path and name' }
    }
    if (paths.has(image.path)) return { ok: false, error: 'images[] must not contain duplicate paths' }
    if (!isCoherentProjectChatImageReference(image.path, image.name, projectId, userId)) {
      return { ok: false, error: 'Invalid project chat image reference' }
    }
    paths.add(image.path)
    images.push({ path: image.path, name: sanitizeProjectChatImageName(image.name) })
  }

  if (!body && images.length === 0) return { ok: false, error: 'Message body or images are required' }
  return { ok: true, data: { body, images } }
}

function numberFrom(value: unknown): number | null {
  const number = typeof value === 'number' ? value : typeof value === 'string' && value.trim() ? Number(value) : NaN
  return Number.isSafeInteger(number) && number >= 0 ? number : null
}

export function extractProjectChatStorageMetadata(
  value: unknown,
): { size: number | null; mimeType: ProjectChatImageMimeType | null } {
  if (!value || typeof value !== 'object') return { size: null, mimeType: null }
  const object = value as Record<string, unknown>
  const metadata = object.metadata && typeof object.metadata === 'object'
    ? object.metadata as Record<string, unknown>
    : null
  const size = numberFrom(object.size) ?? numberFrom(object.contentLength) ??
    numberFrom(metadata?.size) ?? numberFrom(metadata?.contentLength)
  const rawMime = [object.contentType, object.mimeType, object.mimetype, metadata?.mimetype, metadata?.mimeType, metadata?.contentType]
    .find(value => typeof value === 'string' && value.trim())
  const normalizedMime = typeof rawMime === 'string' ? rawMime.trim().toLowerCase() : ''
  const mimeType = PROJECT_CHAT_IMAGE_MIME_TYPES.includes(normalizedMime as ProjectChatImageMimeType)
    ? normalizedMime as ProjectChatImageMimeType
    : null
  return { size, mimeType }
}

export function toStoredProjectChatImage(
  path: string,
  name: string,
  storageInfo: unknown,
): StoredChatImage | null {
  const metadata = extractProjectChatStorageMetadata(storageInfo)
  if (!metadata.mimeType || metadata.size === null || metadata.size < 1 || metadata.size > PROJECT_CHAT_MAX_IMAGE_BYTES) {
    return null
  }
  const safeName = sanitizeProjectChatImageName(name)
  return safeName ? { path, name: safeName, mimeType: metadata.mimeType, size: metadata.size } : null
}
